{% set name = "pyobjc-framework-Quartz" %}
{% set version = "12.0" %}

package:
  name: pyobjc-framework-quartz
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_').lower() }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 5bcb9e78d671447e04d89e2e3c39f3135157892243facc5f8468aa333e40d67f

build:
  number: 0
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyobjc-core >=11.1
    - pyobjc-framework-cocoa >=11.1

test:
  imports:
    - Quartz
    - Quartz.CoreGraphics
    - Quartz.CoreVideo
    - Quartz.ImageIO
    - Quartz.ImageKit
    - Quartz.PDFKit
    - Quartz.QuartzComposer
    - Quartz.QuartzCore
    - Quartz.QuartzFilters
    - Quartz.QuickLookUI

about:
  home: https://github.com/ronaldoussoren/pyobjc
  dev_url: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-framework-Quartz
  doc_url: https://pyobjc.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Quartz frameworks on Mac OS X

extra:
  recipe-maintainers:
    - jschueller
    - hhslepicka
    - thewchan
