{% set name = "pyobjc-framework-Quartz" %}
{% set version = "7.3" %}

package:
  name: pyobjc-framework-quartz
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98812844c34262def980bdf60923a875cd43428a8375b6fd53bd2cd800eccf0b

build:
  number: 1
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyobjc-framework-cocoa

test:
  imports:
    - Quartz
    - Quartz.CoreGraphics
    - Quartz.CoreVideo
    - Quartz.ImageIO
    - Quartz.ImageKit
    - Quartz.PDFKit
    - Quartz.QuartzComposer
    - Quartz.QuartzCore
    - Quartz.QuartzFilters
    - Quartz.QuickLookUI

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Quartz frameworks on Mac OS X

extra:
  recipe-maintainers:
    - thewchan
    - jschueller
    - hhslepicka
