schema_version: 1

context:
  name: pyobjc-framework-Quartz
  version: 12.0

package:
  name: pyobjc-framework-quartz
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name.replace('-', '_').lower() }}/${{ name.replace('-', '_') | lower }}-${{ version }}.tar.gz
  sha256: 5bcb9e78d671447e04d89e2e3c39f3135157892243facc5f8468aa333e40d67f
  file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 0
  skip: (not osx) or match(python, ">=2,<3") or python_impl == 'pypy' or (arm64 and match(python, "<3.9"))
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: 
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyobjc-core >=${{ version }}
    - pyobjc-framework-cocoa >=${{ version }}

tests:
  - python:
      pip_check: true
      imports:
        - Quartz
        - Quartz.CoreGraphics
        - Quartz.CoreVideo
        - Quartz.ImageIO
        - Quartz.ImageKit
        - Quartz.PDFKit
        - Quartz.QuartzComposer
        - Quartz.QuartzCore
        - Quartz.QuartzFilters
        - Quartz.QuickLookUI

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Quartz frameworks on Mac OS X
  homepage: https://github.com/ronaldoussoren/pyobjc
  repository: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-framework-Quartz
  documentation: https://pyobjc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jschueller
    - hhslepicka
    - thewchan
