schema_version: 1

context:
  name: pyobjc-framework-Quartz
  version: 12.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyobjc_framework_quartz-${{ version }}.tar.gz
  sha256: 5bcb9e78d671447e04d89e2e3c39f3135157892243facc5f8468aa333e40d67f

build:
  number: 1
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    # force ignoring invalid compiler flag (-Wl,-export-dynamic)
    - export CFLAGS="${CFLAGS} -Wno-unused-command-line-argument"  # [py == 37 or py == 38]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [(not osx) or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - if: build_platform != target_platform
      then: 
        - python
        - cross-python_${{ target_platform }}
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyobjc-core >=${{ version }}
    - pyobjc-framework-cocoa >=${{ version }}

tests:
  - python:
      pip_check: true
      imports:
        - Quartz
        - Quartz.CoreGraphics
        - Quartz.CoreVideo
        - Quartz.ImageIO
        - Quartz.ImageKit
        - Quartz.PDFKit
        - Quartz.QuartzComposer
        - Quartz.QuartzCore
        - Quartz.QuartzFilters
        - Quartz.QuickLookUI

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Quartz frameworks on Mac OS X
  homepage: https://github.com/ronaldoussoren/pyobjc
  repository: https://github.com/ronaldoussoren/pyobjc/tree/master/pyobjc-framework-Quartz
  documentation: https://pyobjc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jschueller
    - hhslepicka
    - thewchan
